# Generated by Django 5.2 on 2026-05-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entorno_app', '0002_categoria_reloj_categorias_perfilcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reloj',
            name='categorias',
        ),
        migrations.CreateModel(
            name='RelojCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relojes', to='entorno_app.categoria')),
                ('reloj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='entorno_app.reloj')),
            ],
            options={
                'verbose_name_plural': 'Reloj Categorias',
                'unique_together': {('reloj', 'categoria')},
            },
        ),
    ]
